openapi: 3.0.0
info:
  title: Incidents API
  description: API para gestionar incidentes de equipos de trabajo
  version: "1.0.0"

servers:
  - url: http://localhost:3000

paths:
  /incidents:
    get:
      summary: Obtener todos los incidentes
      responses:
        "200":
          description: Lista de incidentes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Incident"
    post:
      summary: Crear un nuevo incidente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IncidentCreate"
      responses:
        "201":
          description: Incidente creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        "400":
          description: Error de validación
        "500":
          description: Error interno

  /incidents/{id}:
    get:
      summary: Obtener un incidente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Incidente encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        "404":
          description: Incidente no encontrado
    put:
      summary: Actualizar el estado de un incidente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IncidentUpdate"
      responses:
        "200":
          description: Incidente actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Incident"
        "400":
          description: Error de validación o cuerpo inválido
        "404":
          description: Incidente no encontrado
        "500":
          description: Error interno
    delete:
      summary: Eliminar un incidente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Incidente eliminado
        "404":
          description: Incidente no encontrado
        "500":
          description: Error interno

components:
  schemas:
    Incident:
      type: object
      properties:
        id:
          type: integer
        reporter:
          type: string
        description:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time

    IncidentCreate:
      type: object
      required:
        - reporter
        - description
      properties:
        reporter:
          type: string
          example: "Juan Pérez"
        description:
          type: string
          example: "La impresora no imprime y hace mucho ruido"

    IncidentUpdate:
      type: object
      properties:
        status:
          type: string
          example: "en proceso"
