FROM oven/bun:1.0.25

WORKDIR /app

# No copiamos nada porque montaremos el volumen en desarrollo
# Solo instalamos dependencias para cache

COPY package*.json ./
RUN bun install

EXPOSE 3000

# El comando para ejecutar está en docker-compose (bun --hot run src/index.ts)